import React from "react";
import { Phone, Mail, MapPin, Instagram, Clock, MessageCircle } from "lucide-react";
import product1 from "@/assets/our-product-1.jpg";

// Replace with your real image or keep placeholder
const ctaBgImage = product1; 

const ContactSection = () => {
  return (
    <section id="contact" className="w-full py-20 md:py-28 bg-[#FCFAF8]">
      <div className="container mx-auto px-4 md:px-8">
        {/* 
           1. Removed 'items-start'. 
           Grid by default stretches children to equal height. 
        */}
        <div className="grid lg:grid-cols-2 gap-12 lg:gap-16">
          
          {/* LEFT COLUMN: CTA Card */}
          {/* 
             2. Added 'h-full'. 
             This ensures the card fills the entire height of the grid row 
             generated by the Right Column's content.
          */}
          <div 
            className="relative w-full h-full min-h-[500px] rounded-[24px] overflow-hidden p-12 flex flex-col items-center justify-center text-center gap-6"
            style={{
              background: `linear-gradient(180deg, rgba(204, 119, 0, 0.90) 0%, rgba(92, 54, 0, 0.95) 100%), url(${ctaBgImage})`,
              backgroundSize: 'cover',
              backgroundPosition: 'center',
              // Removed fixed minHeight from here so it follows the right column
            }}
          >
            {/* Icon Circle */}
            <div className="w-20 h-20 rounded-full bg-[#FCFAF8]/50 flex items-center justify-center backdrop-blur-sm">
              <MessageCircle size={36} className="text-[#FCFAF8]" />
            </div>

            {/* Title */}
            <h3 className="text-[#FCFAF8] text-3xl font-['Plus_Jakarta_Sans'] font-bold leading-tight">
              Pesan Sekarang via WhatsApp
            </h3>

            {/* Description */}
            <p className="text-[#FCFAF8]/80 text-base font-['Plus_Jakarta_Sans'] font-semibold leading-relaxed max-w-sm">
              Dapatkan konsultasi gratis dan penawaran terbaik untuk kebutuhan katering Anda
            </p>

            {/* Button */}
            <a
              href="https://wa.me/6281323966051?text=Halo Fameals, saya ingin bertanya tentang menu katering"
              target="_blank"
              rel="noopener noreferrer"
              className="mt-4 inline-flex items-center gap-2 px-8 py-4 bg-[#FCFAF8] rounded-full hover:bg-[#fcfaf8]/90 transition-all duration-300 group"
            >
              <Phone size={20} className="text-[#FF9500] fill-current" />
              <span className="text-[#FF9500] text-base font-['Plus_Jakarta_Sans'] font-semibold">
                Chat via WhatsApp
              </span>
            </a>
          </div>

          {/* RIGHT COLUMN: Contact Info */}
          <div className="flex flex-col items-start gap-4">
            
            {/* Badge */}
            <div className="inline-flex items-center px-3 py-1 bg-[#EE7C2B]/10 rounded-full mb-2">
              <span className="text-[#FF9500] text-sm font-['Plus_Jakarta_Sans'] font-semibold uppercase tracking-wider">
                Contact
              </span>
            </div>

            {/* Title */}
            <h2 className="text-[#32241B]/90 text-3xl md:text-4xl font-['Plus_Jakarta_Sans'] font-bold leading-tight">
              It's Our Pleasure to Assist You.
            </h2>

            {/* Description */}
            <p className="text-[#6F645D] text-lg font-['Plus_Jakarta_Sans'] font-normal leading-relaxed mb-8">
              Hubungi kami untuk informasi lebih lanjut, pemesanan, atau konsultasi menu 
              sesuai kebutuhan Anda. Tim kami siap membantu dengan senang hati dan responsif.
            </p>

            {/* Contact List */}
            <div className="w-full flex flex-col gap-6">
              
              {/* WhatsApp */}
              <a 
                href="https://wa.me/6281323966051"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-4 p-4 rounded-xl bg-[#F2EEE9]/50 hover:bg-[#F2EEE9] transition-colors"
              >
                <div className="w-12 h-12 rounded-full bg-[#EE7C2B]/10 flex items-center justify-center shrink-0">
                  <Phone size={22} className="text-[#FF9500]" />
                </div>
                <div className="flex flex-col">
                  <span className="text-[#CC7700] text-sm font-['Plus_Jakarta_Sans']">WhatsApp</span>
                  <span className="text-[#32241B]/90 text-base font-['Plus_Jakarta_Sans'] font-semibold">0813-2396-6051</span>
                </div>
              </a>

              {/* Email */}
              <a 
                href="mailto:famealsfoods@gmail.com"
                className="flex items-center gap-4 p-4 rounded-xl bg-[#F2EEE9]/50 hover:bg-[#F2EEE9] transition-colors"
              >
                <div className="w-12 h-12 rounded-full bg-[#EE7C2B]/10 flex items-center justify-center shrink-0">
                  <Mail size={22} className="text-[#FF9500]" />
                </div>
                <div className="flex flex-col">
                  <span className="text-[#CC7700] text-sm font-['Plus_Jakarta_Sans']">Email</span>
                  <span className="text-[#32241B]/90 text-base font-['Plus_Jakarta_Sans'] font-semibold">famealsfoods@gmail.com</span>
                </div>
              </a>

              {/* Instagram */}
              <a 
                href="https://instagram.com/fameals"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-4 p-4 rounded-xl bg-[#F2EEE9]/50 hover:bg-[#F2EEE9] transition-colors"
              >
                <div className="w-12 h-12 rounded-full bg-[#EE7C2B]/10 flex items-center justify-center shrink-0">
                  <Instagram size={22} className="text-[#FF9500]" />
                </div>
                <div className="flex flex-col">
                  <span className="text-[#CC7700] text-sm font-['Plus_Jakarta_Sans']">Instagram</span>
                  <span className="text-[#32241B]/90 text-base font-['Plus_Jakarta_Sans'] font-semibold">@fameals</span>
                </div>
              </a>

              {/* Location */}
              <div className="flex items-center gap-4 p-4 rounded-xl bg-[#F2EEE9]/50">
                <div className="w-12 h-12 rounded-full bg-[#EE7C2B]/10 flex items-center justify-center shrink-0">
                  <MapPin size={22} className="text-[#FF9500]" />
                </div>
                <div className="flex flex-col">
                  <span className="text-[#CC7700] text-sm font-['Plus_Jakarta_Sans']">Lokasi</span>
                  <span className="text-[#32241B]/90 text-base font-['Plus_Jakarta_Sans'] font-semibold">Komplek Panghegar Permai, Kota Bandung</span>
                </div>
              </div>

              {/* Hours */}
              <div className="flex items-center gap-4 p-4 rounded-xl bg-[#F2EEE9]/50">
                <div className="w-12 h-12 rounded-full bg-[#EE7C2B]/10 flex items-center justify-center shrink-0">
                  <Clock size={22} className="text-[#FF9500]" />
                </div>
                <div className="flex flex-col">
                  <span className="text-[#CC7700] text-sm font-['Plus_Jakarta_Sans']">Jam Operasional</span>
                  <span className="text-[#32241B]/90 text-base font-['Plus_Jakarta_Sans'] font-semibold">Senin - Sabtu, 07.00 - 17.00 WIB</span>
                </div>
              </div>

            </div>
          </div>

        </div>
      </div>
    </section>
  );
};

export default ContactSection;